### ISSUE TITLE
Allow transparency for day planner blocks ✨ 

### ISSUE THREAD

**Issue by aknighty74** [ebullient/obsidian-day-planner-og#61]
I have tried several themes that support transparency, but in all of them, the solid color of the bars conflicts with the aftermentioned aspect. Many addons seamlessly integrate with the transparency feature.

Is there a way to enhance the compatibility of the addon with the Translucent window setting in Obsidian's appearance options? An (optional) integration with the Translucent feature would greatly improve day planner's UX.

**Comment by ebullient** [comment]
This should be a matter of updating the css on your end to match what you want. 

That said, can you be more specific? This is not something I've used or loaded. A specific theme would be helpful, as would a small screenshot of which bars you're talking about.

**Comment by ebullient** [comment]
E.g. Something like this: 

https://www.reddit.com/r/ObsidianMD/comments/y3dzy0/anyway_to_get_the_editor_to_be_translucent_like/

The default colors: 

```css
#day-planner-timeline-container {
    --skobeloff: #006466ff;
    --midnight-green-eagle-green: #065a60ff;
    --midnight-green-eagle-green-2: #0b525bff;
    --midnight-green-eagle-green-3: #144552ff;
    --charcoal: #1b3a4bff;
    --prussian-blue: #212f45ff;
    --space-cadet: #272640ff;
    --dark-purple: #312244ff;
    --russian-violet: #3e1f47ff;
    --russian-violet-2: #4d194dff;
}
```

You could replace these values with your own, (adjusting the [FF at the end](https://www.digitalocean.com/community/tutorials/css-hex-code-colors-alpha-values)):

    --russian-violet-2: #4d194d80;
